### ISSUE TITLE
Order elections by "charisma"

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/aggregator-api#109]
When we serve up an array of ballots taking place on a date, it would be nice for data consumers if they were ordered _roughly_ in terms of importance or how much people care. That way in applications that simply consume the array and present the elections one-by-one, they're pre-sorted into a vaguely sensible order and we're not forcing that decision process onto every client app that consumes it. For example, this

![Screenshot at 2019-11-21 13-13-14](https://user-images.githubusercontent.com/6025893/69341077-c46b9500-0c60-11ea-9566-b5b9e91def90.png)

is nicer than this:

![Screenshot at 2019-11-21 13-13-36](https://user-images.githubusercontent.com/6025893/69341083-c7ff1c00-0c60-11ea-9134-34488a066f25.png)

A good first bash at this would be to say scheduled elections are more charismatic than by-elections and national elections have more charisma than local ones. There's probably scope for more granularity than that..

**Comment by symroe** [comment]
We [sort of have this in WCIVF](https://github.com/DemocracyClub/WhoCanIVoteFor/search?q=weight&unscoped_q=weight), but it's fairly ad-hoc, so I expect thinking about it more systematically here would be a good idea.
