### ISSUE TITLE
staging deploys

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/aggregator-api#17]
Deploying to staging before we deploy to prod is useful because it means if it fails we don't break prod, but it would be useful to be able to test certain changes on staging more easily before merging to master. Ideas:

* Have a way to deploy to (a) staging instance in a PR (e.g: "[staging] my PR title")
* Set up another branch deploy rule in Circle so we can (for example) merge to `develop` to test on staging, then merge to master once we're happy with it

**Comment by symroe** [comment]
We have addressed this mostly, but in slightly different ways:

1. a merge to master does a stage deploy and runs some smoke tests before deploying to prod
2. we've made it much easier for a dev to deploy to a prod-like dev environment manually, so if there are QA/testing related tasks that need a deploy, deploying a PR branch to a dev env is the best way of doing that. 

We could look in to automating this using the PR title or whatever as Chris suggests, but at the moment this doesn't fall on the right side of the tooling cost / benefit equation.
