### ISSUE TITLE
Expose previous party affiliation in public API

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/aggregator-api#286]
Party of https://github.com/DemocracyClub/yournextrepresentative/issues/1765

Once https://github.com/DemocracyClub/WhoCanIVoteFor/issues/1077 is deployed, we need to add the new field to the API response here:

- [x] Update WCIVF fixtures
- [x] Check if the stitcher class needs updating
- [x] Document (and add a note)

**Comment by VirginiaDooley** [comment]
> Yes, it's a property of the "candidacy" (Membership in the YNR world). The devs.DC API has a candidates response that's basically a list of candidacies, with a person key inside. We want the previous party info to be on the same level as list_position, party and person not inside person, because person is  just stuff about that person, not that person in this election, if that makes sense.
> 
> The fixtures and test data is a little clunky to work with, as you have to edit loads of files, but yes, that PR is about the right thing to copy for the work.
> 
> I think previous_party_affiliations should _always exist and be null, and then be a list of party IDs when it does exist. That means updating all the sandbox responses, fixtures, etc to add that key. It would be great if at least one of the sandbox responses included some test data, so we can use that when working on the widget
