### ISSUE TITLE
what should we do with postcodes split across local auths

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/aggregator-api#38]
e.g: TA19 9NN
At the moment, we don't assign this to a council but we do assign it a ward (and candidates) based on postcode centroid. However, even if we don't know enough to give an address picker response, we do know enough to be sure that there isn't a one-to one mapping from postcode --> ward.

What should we do in this case?

**Comment by symroe** [comment]
I _think_ the work on WDIV has fixed this. At the time of writing the sample postcode above is an address picker. Pinging @GeoWill to confirm

**Comment by GeoWill** [comment]
Yep. We show an addresspicker, and then on the `/address/<uprn>/` links we show the correct ward/council.
